name: Quality Assurance

on: [pull_request, workflow_call]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql:
    name: Analyze with codeql
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  quality-assurance:
    name: Quality Assurance

    # TODO(dmu) LOW: Consider using Debian Buster (the same as docker image is based on) if it is easy to do
    runs-on: ubuntu-latest
    container: node:18.0.0

    steps:
      # TODO(dmu) LOW: Implement caching
      - uses: actions/checkout@v4

      - name: Install
        run: HUSKY=0 npm install --legacy-peer-deps

      # - name: Lint
      #   run: npm run lint

      - name: Test
        run: npm run test
